# Use postgres/example user/password credentials
version: '3.6'

services:

  db:
    container_name: perm-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: zaq1@WSX
      POSTGRES_DB: server
      PGDATA: /data/pgdata
    volumes:
        - ../server/pgdata:/data/pgdata
    ports: 
        - "5444:5432"