POST http://localhost:5000/todos HTTP/1.1
content-type: application/json

{
    "text": "aaaa"
}

###

GET http://localhost:5000/todos HTTP/1.1

###

GET http://localhost:5000/todos/4 HTTP/1.1

###

DELETE  http://localhost:5000/todos/8 HTTP/1.1